#spring:
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false

spring:    
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://10.51.103.46:5432/dams_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: dams_dev
    password: dams_dev
  application:
    name: springbootstart    
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    
server:
  port: 8080
  
#eureka:
#  client:
#    service-url:
#      defaultZone: http://10.122.4.73:3333/eureka
#    registerWithEureka: false
#    fetchRegistry:  false
    